/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import pruebas.pruebas;

/**
 *
 * @author Francisco
 */
public class puzzle_solver extends javax.swing.JFrame {

    /**
     * Creates new form puzzle_solver
     */
    public puzzle_solver() {
        initComponents();
    }
    
    public void printResults(Process process) throws IOException {
        File fl = new File("C:\\Users\\Francisco\\Documents\\Semestre_9\\IA\\lisp\\somefile.dat");
        String rFin;
        try (Scanner sc = new Scanner(fl)) {
            String line;
            rFin = "";
            boolean aux = true;
            int id;
            int idNext = 0;
            int padre;
            int nivel;
            int mov;
            int ord[][] = new int[3][3];
            while (sc.hasNextLine()) {
                line = sc.nextLine();
                if(sc.hasNextLine()){
                    line = line.substring(2);
                    line = line.substring(0,line.length()-2);
                    StringTokenizer st = new StringTokenizer(line, " ");
                    StringBuilder res;
                    res = new StringBuilder("\n\n");
                    if(aux){
                        aux = false;
                        id = parseInt(st.nextToken(" "));
                        idNext = parseInt(st.nextToken(" "));
                        nivel = parseInt(st.nextToken(" "));
                        res.append("ID: ").append(id).append("  Padre: ").append(idNext).append("  Nivel:  ").append(nivel).append("\n");
                        st.nextToken(" ");
                        st.nextToken(" ");    
                        res.append("Movimiento: ").append(st.nextToken(" ")).append("\n\n");
                        st.nextToken(" ");
                        for(int i = 0; i < 3; i++){                        
                            if(i == 0){
                                res.append(st.nextToken(" ").substring(1)).append(" | ").append(st.nextToken(" ")).append(" | ").append(st.nextToken(" ")).append("\n");
                            }else{
                                res.append("----------\n");
                                res.append(st.nextToken(" ")).append(" | ").append(st.nextToken(" ")).append(" | ").append(st.nextToken(" ")).append("\n");
                            }
                        }
                        res.append("\n\n*************************\n\n");
                        rFin = res.toString();
                        //maneja agregar a sol.
                    }else{
                        res = new StringBuilder("\n");
                        id = parseInt(st.nextToken(" "));
                        if(id == idNext){
                            idNext = parseInt(st.nextToken(" "));
                            nivel = parseInt(st.nextToken(" "));
                            res.append("ID: ").append(id).append("  Padre: ").append(idNext).append("  Nivel:  ").append(nivel).append("\n");
                            st.nextToken(" ");
                            st.nextToken(" ");
                            res.append("Movimiento: ").append(st.nextToken(" ")).append("\n\n");
                            st.nextToken(" ");
                            for(int i = 0; i < 3; i++){
                                if(i == 0){
                                    res.append(st.nextToken(" ").substring(1)).append(" | ").append(st.nextToken(" ")).append(" | ").append(st.nextToken(" ")).append("\n");
                                }else{
                                    res.append("----------\n");
                                    res.append(st.nextToken(" ")).append(" | ").append(st.nextToken(" ")).append(" | ").append(st.nextToken(" ")).append("\n");
                                }
                            }
                            res.append("\n\n*************************\n\n");
                            rFin = res.toString() + rFin;
                            //maneja agregar a sol.
                        }
                    }
                }  
            }
        }
        txtRes.setText(rFin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.JButton();
        txt1_1 = new javax.swing.JTextField();
        txt1_2 = new javax.swing.JTextField();
        txt1_3 = new javax.swing.JTextField();
        txt1_4 = new javax.swing.JTextField();
        txt1_5 = new javax.swing.JTextField();
        txt1_6 = new javax.swing.JTextField();
        txt1_7 = new javax.swing.JTextField();
        txt1_8 = new javax.swing.JTextField();
        txt1_9 = new javax.swing.JTextField();
        txt2_8 = new javax.swing.JTextField();
        txt2_9 = new javax.swing.JTextField();
        txt2_1 = new javax.swing.JTextField();
        txt2_2 = new javax.swing.JTextField();
        txt2_3 = new javax.swing.JTextField();
        txt2_4 = new javax.swing.JTextField();
        txt2_5 = new javax.swing.JTextField();
        txt2_6 = new javax.swing.JTextField();
        txt2_7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        txtRes = new javax.swing.JTextArea();
        btnLimpia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn.setText("Resolver!");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        txt1_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt1_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1_2ActionPerformed(evt);
            }
        });

        txt1_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt1_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt1_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt1_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt1_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt1_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt1_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt2_8.setEditable(false);
        txt2_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2_8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2_8.setText("8");

        txt2_9.setEditable(false);
        txt2_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2_9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt2_1.setEditable(false);
        txt2_1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2_1.setText("1");
        txt2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2_1ActionPerformed(evt);
            }
        });

        txt2_2.setEditable(false);
        txt2_2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2_2.setText("2");

        txt2_3.setEditable(false);
        txt2_3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2_3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2_3.setText("3");

        txt2_4.setEditable(false);
        txt2_4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2_4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2_4.setText("4");

        txt2_5.setEditable(false);
        txt2_5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2_5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2_5.setText("5");

        txt2_6.setEditable(false);
        txt2_6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2_6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2_6.setText("6");

        txt2_7.setEditable(false);
        txt2_7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2_7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2_7.setText("7");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Estado Inicial");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Estado Final");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Solución");

        txtRes.setEditable(false);
        txtRes.setColumns(20);
        txtRes.setRows(5);
        txtRes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPane.setViewportView(txtRes);

        btnLimpia.setText("Limpiar");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpia)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpia)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2_1ActionPerformed

    private void txt1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1_2ActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        txtRes.setText("");
        txtRes.setText("");
        txtRes.setText("");
        int[][] puzzle = new int[3][3];
        try{
            puzzle[0][0] = parseInt(txt1_1.getText());
        }catch(NumberFormatException e){
            puzzle[0][0] = 0;
        }
        try{
            puzzle[0][1] = parseInt(txt1_2.getText());
        }catch(NumberFormatException e){
            puzzle[0][1] = 0;
        }
        try{
            puzzle[0][2] = parseInt(txt1_3.getText());
        }catch(NumberFormatException e){
            puzzle[0][2] = 0;
        }  
        try{
            puzzle[1][0] = parseInt(txt1_4.getText());
        }catch(NumberFormatException e){
            puzzle[1][0] = 0;
        }
        try{
            puzzle[1][1] = parseInt(txt1_5.getText());
        }catch(NumberFormatException e){
            puzzle[1][1] = 0;
        }
        try{
            puzzle[1][2] = parseInt(txt1_6.getText());
        }catch(NumberFormatException e){
            puzzle[1][2] = 0;
        }
        try{
            puzzle[2][0] = parseInt(txt1_7.getText());
        }catch(NumberFormatException e){
            puzzle[2][0] = 0;
        }
        try{
            puzzle[2][1] = parseInt(txt1_8.getText());
        }catch(NumberFormatException e){
            puzzle[2][1] = 0;
        }
        try{
            puzzle[2][2] = parseInt(txt1_9.getText());
        }catch(NumberFormatException e){
            puzzle[2][2] = 0;
        }
        //int[][] puzzle2 = {{1, 2, 3},{4, 5, 6},{8, 0, 7}};
        if(revisaPuzzle(puzzle)){
            txtRes.setText("Resolviendo...");
            String txt = "( ";
            for(int i = 0; i<3; i++){
                for(int ii = 0; ii<3; ii++){
                    txt = txt + puzzle[i][ii] + " ";
                }
            }
            txt = txt + ")";
            try {
                try (PrintWriter writer = new PrintWriter("C:\\Users\\Francisco\\Documents\\Semestre_9\\IA\\lisp\\entrada.txt", "UTF-8")) {
                    writer.println(txt);
                }
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(pruebas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(puzzle_solver.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Manda a ejecutar lisp
            try {
                ProcessBuilder pro = new ProcessBuilder();
                pro.command("cmd", "/c" , "clisp puzzle.lisp").directory(new File("C:\\Users\\Francisco\\Documents\\Semestre_9\\IA\\lisp\\"));
                Process proc = pro.start();
                proc.waitFor();
                txtRes.setText("Resuelto!");
                printResults(proc);
            } catch (IOException ex) {
                Logger.getLogger(pruebas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(puzzle_solver.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            txtRes.setText("Puzzle inválido, intente de nuevo");
        }
        //Escribe puzzle en entrada.txt
        
        
    }//GEN-LAST:event_btnActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        // TODO add your handling code here:
        txt1_1.setText("");
        txt1_2.setText("");
        txt1_3.setText("");
        txt1_4.setText("");
        txt1_5.setText("");
        txt1_6.setText("");
        txt1_7.setText("");
        txt1_8.setText("");
        txt1_9.setText("");
    }//GEN-LAST:event_btnLimpiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puzzle_solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puzzle_solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puzzle_solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puzzle_solver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new puzzle_solver().setVisible(true);
        });
    }
    
    public static boolean revisaPuzzle(int[][] arre){
        int inv_count = 0;
        ArrayList<Integer> lst = new ArrayList();
                ArrayList<Integer> aux = new ArrayList();
        for(int i = 1; i < 9; i++){
            aux.add(i);
        }
        for (int i = 0; i < 3; i++)
            for (int j = 0; j < 3; j++)
                if (arre[i][j] > 0 ){
                    lst.add(arre[i][j]);
                }
        if(lst.size() != 8){
            System.out.println("1");
            return false;
        }
        for(int i =0; i < 8; i++){
            if(!lst.contains(aux.get(i))){
                System.out.println("2" + i);
                return false;
            }
            for(int ii = i; ii < 8; ii++){
                if(lst.get(i) > lst.get(ii)){
                    inv_count++;
                }
            }
        }
        return (inv_count%2 == 0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txt1_1;
    private javax.swing.JTextField txt1_2;
    private javax.swing.JTextField txt1_3;
    private javax.swing.JTextField txt1_4;
    private javax.swing.JTextField txt1_5;
    private javax.swing.JTextField txt1_6;
    private javax.swing.JTextField txt1_7;
    private javax.swing.JTextField txt1_8;
    private javax.swing.JTextField txt1_9;
    private javax.swing.JTextField txt2_1;
    private javax.swing.JTextField txt2_2;
    private javax.swing.JTextField txt2_3;
    private javax.swing.JTextField txt2_4;
    private javax.swing.JTextField txt2_5;
    private javax.swing.JTextField txt2_6;
    private javax.swing.JTextField txt2_7;
    private javax.swing.JTextField txt2_8;
    private javax.swing.JTextField txt2_9;
    private javax.swing.JTextArea txtRes;
    // End of variables declaration//GEN-END:variables
}
